[package]
name = "sdrmm-device-espsdr"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sdrmm-wire.workspace = true
sdrmm-device.workspace = true
sdrmm-dsp.workspace = true
serde.workspace = true
serde_json.workspace = true
serialport.workspace = true
tracing.workspace = true
